### ISSUE TITLE
rustls crypto default `aws_lc_rs` v `ring` used in tokio-postgres-rustls

### ISSUE THREAD

**Issue by rbox-risk** [jbg/tokio-postgres-rustls#26]
Hi thanks for helpful crate.

As of `0.23.0` `rustls` defaults to use crypto provider `aws-lc-rs` [rustls crate 0.23.0 docs](https://docs.rs/crate/rustls/0.23.0/features)

This project uses `rustls = { version = "0.23", default-features = false, features = ["std", "logging", "tls12", "ring"] }` enforcing `ring` (without resorting to patches).

Is there a way we can _opt-in_ to previous non-default features such as `ring`, rather than having to _opt-out_ of default features of `rustls` e.g. aligning to `rustls` via a feature? I'm thinking here of other dependencies separate to `tokio-postgres-rustls` that may depend on `default rustls`

**Comment by jbg** [comment]
Do note that `ring` is only used in `dev-dependencies`, because we needed to choose a provider for the tests. If you use the modern Cargo resolver (`edition = "2021"` / `resolver = "2"`), it won't be pulled in unless you are running `cargo test` on this crate, because we don't specify any features at all on our `rustls` dependency in the main `dependencies` section.

Apart from when you're running tests, this crate allows the use of any `rustls` provider and won't pull in any that you don't enable yourself, unless you're using the old pre-2021 resolver.
